### ISSUE TITLE
Assistance with Subscription Payment for AutoHTML Service in Russia

### ISSUE THREAD

**Issue by vlasooff** [tdesero/figma-autohtml-issue-tracker#13]
My name is Vitalii, and I am a developer based in Russia. I have been a fan of your product, AutoHTML, for quite some time, and it has greatly contributed to my projects.

Unfortunately, due to the current sanctions in place, we encounter difficulties in processing payments for your service from Russia. This is disappointing for me, as I value your product and have come to rely on it for my development needs.

I am reaching out to inquire if there could be a solution or alternative payment method made available for users in Russia. I understand the challenges posed by international sanctions, but I believe that finding a way for users like me to continue using your service would be mutually beneficial.

If there are any specific steps or considerations that could be taken to address this issue, I would greatly appreciate your guidance. Your assistance in this matter would not only help me but also contribute to the continued growth and success of your product in the Russian market.

Thank you for your time and consideration. I look forward to hearing from you soon.

**Comment by tdesero** [comment]
Hi Vitalii,
thank you for reaching out to me. I am really sorry to hear, that you are having issues processing payment for the plugin. Currently I am using Figma's build in payment method, which uses Stripe under the hood. You can try to reach out to Figma's support as they potentially have more knowledge about the problem.
Sorry to say that I currently can't do much about it as I think other payment platforms have similar restrictions. I hope that the free features of the plugin can help you at least a little bit in your daily work. I will let you know in case anything changes regarding that issue.
