### ISSUE TITLE
CSS Generation broken for tue/component API

### ISSUE THREAD

**Issue by ManuelNunezFrancisco** [tdesero/figma-autohtml-issue-tracker#16]
Following a snippet (verbatim) of the generated Vue/Component code. There are two issues:

1. indentation is broken (makes it hard to read, becomes a nuisance when  searching for the missing semicolon)
2. Syntax error because of missing semicolon between certain attributes; below "justify-content: centertext-overflow" (semicolon after  'center').

I'm sorry I can't provide the whole model. I can provide more Information if neccessary.

As I often have to regenerate the model, it becomes quite a burden to always manually fix the code. Preview obiously is also impaired...

 ```
   }
 .headline {color: var(--blue-100, #000819);text-align: center;font-family: var(--l-h1-font-family, 'Nunito-Bold', sans-serif);
font-size: var(--l-h1-font-size, 28px);
line-height: var(--l-h1-line-height, 36px);
font-weight: var(--l-h1-font-weight, 700);
      position: relative;
    align-self: stretch;display: flex;
align-items: center;justify-content: centertext-overflow: ellipsis; overflow: hidden;white-space: nowrap;}
 .text {color: var(--blue-100, #000819);text-align: center;font-family: var(--l-paragraph-font-family, 'Nunito-Regular', sans-serif);
font-size: var(--l-paragraph-font-size
```

**Comment by tdesero** [comment]
Thank you for reporting that bug. I had some issues with code formatting for code snippets in the inspect panel.
Will look into it soon.

**Comment by tdesero** [comment]
@ManuelNunezFrancisco Luckily it was super easy to fix it. I just released a new version. Let me know if it works :)

**Comment by ManuelNunezFrancisco** [comment]
indentation and Syntax fixed. Will post another bug for preview
