### ISSUE TITLE
preview does not work for "pro" version of autohtml with Vue output

### ISSUE THREAD

**Issue by ManuelNunezFrancisco** [tdesero/figma-autohtml-issue-tracker#17]
HTML Output with pro version works (albeit slow for many objects, doesn't usually matter). vue output (component API, either with or without nested components) will draw the text "undefined" with an enclosing green box. It seems to be broken for every component I try to generate.

vue output in the free version never had this problem.

<img width="450" alt="Bildschirmfoto 2024-02-28 um 20 43 35" src="https://github.com/tdesero/figma-autohtml-issue-tracker/assets/55431792/72c21579-131e-4746-9228-7d78ebf40a9c">

**Comment by tdesero** [comment]
I just checked and I couldn't fully reproduce it. Does the preview appear if you wait for a few seconds after selecting a frame?

**Comment by tdesero** [comment]
In the meantime I figured out there was a bug when selecting groups. This could potentially have been the reason to have an empty preview in your case. I published a bugfix for that.

Do still have the issue?

**Comment by ManuelNunezFrancisco** [comment]
Does not happen anymore - I'll keep you updated.
